[build]
builder = "dockerfile"
dockerfilePath = "AppBlueprint.ApiService/Dockerfile"

[deploy]
startCommand = "dotnet AppBlueprint.ApiService.dll"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

